-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT USER_INFO.USER_ID) AS USERS
FROM ONLINE_SALE JOIN (SELECT USER_ID,GENDER FROM USER_INFO WHERE GENDER = 0 OR GENDER = 1) AS USER_INFO
ON USER_INFO.USER_ID = ONLINE_SALE.USER_ID 
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER