-- 코드를 입력하세요
SELECT CAR.CAR_ID, CAR.CAR_TYPE, ROUND(CAR.DAILY_FEE*30*(100-DIS.DISCOUNT_RATE)/100, 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS CAR
JOIN (SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = '30일 이상') AS DIS
ON CAR.CAR_TYPE = DIS.CAR_TYPE
WHERE CAR.CAR_ID NOT IN (SELECT HIS.CAR_ID
                         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HIS
                         WHERE HIS.END_DATE >= '2022-11-01' AND HIS.START_DATE < '2022-12-01') AND CAR.CAR_TYPE IN ('세단','SUV')
GROUP BY CAR.CAR_ID
HAVING FEE >=500000 AND FEE <= 1999999
ORDER BY FEE DESC ,CAR_TYPE ASC, CAR_ID DESC 

