-- 코드를 입력하세요
SELECT concat("/home/grep/src/",B.BOARD_ID,"/",F.FILE_ID,F.FILE_NAME,F.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE as F
    LEFT JOIN USED_GOODS_BOARD as B
    ON F.BOARD_ID = B.BOARD_ID
WHERE B.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY F.FILE_ID DESC

