-- 코드를 입력하세요
SELECT FLAVOR
FROM 
    (SELECT FH.FLAVOR , (FH.TOTAL_ORDER + JULY.TOTAL_ORDER) AS TOTAL_ORDER
     FROM 
        (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
        FROM FIRST_HALF 
        GROUP BY FLAVOR) AS FH
        JOIN
        (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
        FROM JULY
        GROUP BY FLAVOR) AS JULY
        ON FH.FLAVOR = JULY.FLAVOR
        ORDER BY TOTAL_ORDER DESC LIMIT 3
     ) AS TOPTHREE


