-- 코드를 입력하세요
SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK JOIN (SELECT * FROM BOOK_SALES WHERE SUBSTR(SALES_DATE,1,7) = '2022-01') AS S ON BOOK.BOOK_ID = S.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY