-- 코드를 입력하세요
SELECT AUTHOR.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES.SALES * BOOK.PRICE) AS TOTAL_SALES
FROM BOOK JOIN (SELECT * FROM BOOK_SALES WHERE MONTH(SALES_DATE) = '01')AS SALES ON BOOK.BOOK_ID = SALES.BOOK_ID JOIN AUTHOR ON AUTHOR.AUTHOR_ID = BOOK.AUTHOR_ID
GROUP BY AUTHOR_ID , CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC
