-- 코드를 입력하세요
SELECT HISTORY_ID , ROUND(DAILY_FEE* (DATEDIFF(END_DATE,START_DATE)+1) *(case 
    when DATEDIFF(END_DATE,START_DATE)+1 < 7 then 1
    when DATEDIFF(END_DATE,START_DATE)+1 < 30 then 0.95
    when DATEDIFF(END_DATE,START_DATE)+1 < 90 then 0.92
    else 0.85 end)) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HIS
JOIN CAR_RENTAL_COMPANY_CAR AS CAR
ON HIS.CAR_ID = CAR.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS DIS
ON DIS.CAR_TYPE = CAR.CAR_TYPE

WHERE CAR.CAR_TYPE = "트럭"
GROUP BY HISTORY_ID
ORDER BY FEE DESC, HISTORY_ID DESC