-- 코드를 입력하세요
SELECT APNT_NO , PT_NAME,  APT.PT_NO, APT.MCDP_CD, DR_NAME, APNT_YMD
FROM PATIENT JOIN (SELECT * FROM APPOINTMENT WHERE APNT_CNCL_YN = 'N' AND MCDP_CD = 'CS' AND SUBSTR(APNT_YMD,1,10) = '2022-04-13') AS APT ON APT.PT_NO = PATIENT.PT_NO  JOIN DOCTOR ON APT.MDDR_ID = DOCTOR.DR_ID
GROUP BY APNT_NO
ORDER BY APNT_YMD