-- 코드를 입력하세요
SELECT BOOK_ID , AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE,'%Y-%m-%d')AS PUBLISHED_DATE
FROM AUTHOR JOIN (SELECT * FROM BOOK WHERE CATEGORY = '경제')AS A ON AUTHOR.AUTHOR_ID = A.AUTHOR_ID
ORDER BY PUBLISHED_DATE