-- 코드를 입력하세요
SELECT A.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, SCORE
FROM  (
        SELECT ROUND(SUM(REVIEW_SCORE) / COUNT(REST_ID),2)AS SCORE , REST_ID
        FROM REST_REVIEW
        GROUP BY REST_ID
     )  AS A JOIN REST_INFO ON A.REST_ID = REST_INFO.REST_ID
WHERE ADDRESS LIKE "서울%"
ORDER BY SCORE DESC, FAVORITES DESC